language: php
sudo: false

## Cache composer bits
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

## PHP versions we test against
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - nightly
  - hhvm

## Build matrix for lowest and highest possible targets
matrix:
  include:
    - php: 5.4
      env: dependencies=lowest
    - php: 5.5
      env: dependencies=lowest
    - php: 5.6
      env: dependencies=lowest
    - php: 7
      env: dependencies=lowest
    - php: nightly
      env: dependencies=lowest
    - php: hhvm
      env: dependencies=lowest
    - php: 5.4
      env: dependencies=highest
    - php: 5.5
      env: dependencies=highest
    - php: 5.6
      env: dependencies=highest
    - php: 7
      env: dependencies=highest
    - php: nightly
      env: dependencies=highest
    - php: hhvm
      env: dependencies=highest

## Update composer and run the appropriate composer command
before_script:
  - composer self-update -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - if [ -z "$dependencies" ]; then composer install; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update -n; fi;
  - composer show -i

## Run the actual test
script: make travis

after_script: make travis-coverage
