language: php

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache/files

## Build matrix for lowest and highest possible targets
matrix:
  include:
    - php: 7.1
      env:
        - qaExtended=true
    - php: 7.2
      env:
        - dropPlatform=false
    - php: 7.3
      env:
        - dropPlatform=false
    - php: 7.1
      env:
        - dependencies=lowest
    - php: 7.2
      env:
        - dependencies=lowest
        - dropPlatform=false
    - php: 7.3
      env:
        - dependencies=lowest
        - dropPlatform=false
    - php: 7.1
      env:
        - dependencies=highest
    - php: 7.2
      env:
        - dependencies=highest
        - dropPlatform=false
    - php: 7.3
      env:
        - dependencies=highest
        - dropPlatform=false
    - php: 7.1
      env:
        - csCheck=true

## Install or update dependencies
install:
  - composer validate
  - if [ -z "$dropPlatform" ]; then composer config --unset platform.php; fi;
  - if [ -z "$qaExtended" ]; then phpenv config-rm xdebug.ini || :; fi;
  - if [ -z "$dependencies" ]; then composer install --prefer-dist; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-dist -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update --prefer-dist -n; fi;
  - composer show

## Run the actual test
script:
  - if [ -z "$qaExtended" && -z "$csCheck" ]; then make ci; fi;
  - if [ "$qaExtended" = "true" ]; then make ci-extended; fi;
  - if [ "$csCheck" = "true" ]; then make cs; fi;

## Gather coverage and set it to coverage servers
after_script: if [ "$qaExtended" = "true" ]; then make ci-coverage; fi;
